
CREATE TABLE ARENA
(
	_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	LOCATION TEXT
);

/
CREATE TABLE GAME
(
	_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DATE TEXT NOT NULL,
	TIME TEXT NOT NULL,
	TITLE TEXT NOT NULL,
	PLACE INTEGER DEFAULT 0 NOT NULL,
	TEAM_A INTEGER,
	TEAM_B INTEGER,
	CONSTRAINT GAME_ID UNIQUE (DATE, TIME, PLACE)
);

/
CREATE TABLE PERSON
(
	_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	ORGANIZATION INTEGER
);

/

CREATE TABLE POINT
(
	_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	GAME INTEGER NOT NULL,
	PERSON INTEGER,
	SECTION TEXT,
	TIME INTEGER DEFAULT 0,
	AMOUNT INTEGER DEFAULT 1
);

/
CREATE TABLE TEAM
(
	_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	LOCATION TEXT,
	LEADER TEXT,
	CONTACT TEXT
);

